defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "default"

title: "Elements C++ GUI library"
description: >-
  Elements is a lightweight, fine-grained, HDPI capable, resolution
  independent, modular C++ GUI library.
url: "https://cycfi.github.io"
baseurl: "/elements"

remote_theme: adobe/hyde-theme@v1.0.0
adobe_hyde:
  header_image: "/assets/images/elements.png"

plugins:
- jemoji

# Using GitHub Jekyll v3.9.0, these are not ignored by default
exclude:
- elements.code-workspace
- Gemfile
- Gemfile.lock
- jekyll.sh
- README.md
