source "https://rubygems.org"

gem "jekyll", "3.9.0"

group :jekyll_plugins do
  gem "jekyll-feed", "0.13.0"
  gem "jekyll-sitemap", "1.4.0"
  gem "jekyll-theme-cayman", "0.1.1"
  gem "jemoji", "0.11.1"
  gem "kramdown-parser-gfm", "1.1.0"
end
